# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra' # Webアプリケーションフレームワーク
gem 'httpclient' # httpアクセスを簡易にするライブラリ
gem 'thin' # Rubyを実行する軽量なWebサーバ

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
